# Generated by Django 6.0.5 on 2026-05-27 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('suspicious_rows', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.CharField(default='analyst', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('activity_description', models.TextField()),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_unit', models.CharField(choices=[('kwh', 'kWh'), ('mwh', 'MWh'), ('liter', 'Liter'), ('kg', 'Kilogram'), ('tonne', 'Tonne'), ('km', 'Kilometer'), ('mile', 'Mile'), ('m3', 'Cubic Meter')], max_length=20)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('source_type', models.CharField(max_length=20)),
                ('source_row_id', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspicious', 'Suspicious')], default='pending', max_length=20)),
                ('suspicion_reason', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.client')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='ingestion.ingestionbatch')),
            ],
        ),
    ]
